#!/bin/bash
clear
echo -e "\e[1;35m   AJI MASTER PREMIUM INSTALLER\e[0m"
echo -e "\e[1;35m ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
read -p " Apakah kamu reseller? (iya/bukan): " jawab
if [[ "$jawab" == "iya" ]]; then
read -sp " Masukkan Password Reseller: " pass
echo ""
if [[ "$pass" == "sewasc01" ]]; then
read -p " Mau aktif berapa hari? (angka saja): " jumlah_hari
mkdir -p /etc/aji
echo "$jumlah_hari" > /etc/aji_expire_type
date +%s > /etc/aji/install_date
else
echo " Password Salah!"; exit 1
fi
else
read -sp " Masukkan Password Owner: " pass
echo ""
if [[ "$pass" == "owner01" ]]; then
mkdir -p /etc/aji
echo "unlimited" > /etc/aji_expire_type
else
echo " Password Salah!"; exit 1
fi
fi
echo -e "\e[1;32m Proses Install Sedang Berjalan...\e[0m"
apt update -y && apt install curl wget sudo -y
wget -q -O /usr/bin/menu "https://raw.githubusercontent.com/arturrohim16-cloud/Ajimaster-scriot/refs/heads/main/Scriptku"
chmod +x /usr/bin/menu
clear
echo -e "\e[1;35m ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
echo -e "\e[1;32m       INSTALL SELESAI!\e[0m"
echo -e "\e[1;33m       SILAKAN KETIK: menu\e[0m"
echo -e "\e[1;35m ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\e[0m"
